apiVersion: v1
kind: Pod
metadata:
  name: client-postgres
spec:
  containers:
  - name: client-container
    image: postgres:15
    env:
      - name: POSTGRES_PASSWORD 
        value: postgres
      - name: POSTGRES_USER
        value: postgres