apiVersion: v1
kind: Pod
metadata:
  name: client-postgres
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: postgres-pvc
  containers:
  - name: client-container
    image: postgres:15
    env:
      - name: POSTGRES_PASSWORD 
        value: postgres
      - name: POSTGRES_USER
        value: postgres

    volumeMounts:
      - mountPath: "/var/lib/postgresql/data/pgdata"
        name: pv-storage