apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dev
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  storageClassName: hostpath
  local:
    path: /run/desktop/mnt/host/c/Users/Ange TAFFO/Documents/postgres-k8s/dev
    
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop
