apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  type: NodePort
  selector:
    app: postgres-dev
    # postgres-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5432
      targetPort: 5432
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30020

#To Create a namespace write the command: kubectl create namespace your-namespace
#To Create component in a namespace write the command: kubectl apply -f your_config.yaml --namespace=your-namespace
#To see if all pod or services are running the namespace write the command: kubectl get all -n namespace-name